# FSMState_RL runtime config
# You can override this file path with env: TITA_RL_CONFIG=/abs/path/to/rl_runtime.yaml

engine_path: /home/raise/Workspaces/tita_rl_sim2sim2real/src/tita_locomotion/engine/policy_estVel.engine
heading_control_stiffness: 0.5
heading_ang_vel_min: -0.5
heading_ang_vel_max: 0.5
history_length: 10
observation_terms: [base_ang_vel, projected_gravity, velocity_commands, joint_pos, joint_vel, last_action, base_lin_vel_xy]

# run() gains
leg_kp: 40.0
leg_kd: 2.5
wheel_kp: 0.0
wheel_kd: 5.0
